# Generated by Django 5.1.2 on 2024-10-18 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitles',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='subtitles',
            name='end_time',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='subtitles',
            name='start_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
